### ISSUE TITLE
What browsers should be supported?

### ISSUE THREAD

**Issue by gourmetseasoningsake** [shtillorg/ML0719-Issues#12]

**Comment by eatpixel** [comment]
Safari (zurück bis iOS 9 - https://david-smith.org/iosversionstats/) 
Firefox (zurück bis 60) - https://static.makeuseof.com/wp-content/uploads/2019/01/firefox-esr-schedule.png
Edge (actual release)
Chrome (actual release - Mobile support bis OS 6) https://fossbytes.com/most-popular-android-versions-always-updated/

Alle nicht unterstützten Browser sollen eine Nachricht erhalten (Error Screen)

**Comment by gourmetseasoningsake** [comment]
Okay, ich übernehme das mal so. Sinnvoll wären allerdings noch die Stats speziell für mammut-lift.ch
Normalerweise haben Hosts Statistiken für einzelne Seiten. Z.B. sind diejenigen von  cyon ziemlich detailreich. Siehe hier: 
![sample-awstats](https://user-images.githubusercontent.com/22403007/63282646-d3782b00-c29e-11e9-9108-ec0b6a225504.jpg)
