### ISSUE TITLE
Bilder der Produkte-Vorschau optimieren

### ISSUE THREAD

**Issue by gourmetseasoningsake** [shtillorg/ML0719-Issues#23]

**Comment by markus-factum** [comment]
![ZSS-preview](https://user-images.githubusercontent.com/58806011/70693338-8b519e00-1cbd-11ea-8e9d-adfd02d95941.png)

Kannst du mal testen mit 1500 Unterfahrbar ZSS, wenn das klappt kann ich die restlichen dann selber hochladen.
