### ISSUE TITLE
Optimierung von Suchergebnis-Darstellung

### ISSUE THREAD

**Issue by gourmetseasoningsake** [shtillorg/ML0719-Issues#26]
Falls hier die generelle "Suche" gemeint ist; Benötigt genauere Angaben zur Darstellung, sofern von den bestehenen Layouts abweichend.

**Comment by gourmetseasoningsake** [comment]
Handelt sich um die Fertigstellung der Suchfunktion.

Als erste Version soll die Marketingseite durchsucht werden können (Teil von ML1219-AL). In einem weiteren Schritt, allerdings nicht Teil des nächsten MSs (ML1219-AL), werden auch die Ersatzteile in die Suche miteingebunden.

**Comment by gourmetseasoningsake** [comment]
Die Suche innerhalb Seiten basiert auf den Meta-Daten. Diese wurden durch ein Such-Feld in "Details" erweitert, um wichtige Daten ausschliesslich für die Suche bereitzustellen. Ob dies als Suche reichen sollte, muss noch besprochen werden (-> neues Issue)

**Comment by markus-factum** [comment]
Suche ist vom Kunden freigegeben, bitte die Lupe wieder einbauen.
