### ISSUE TITLE
Kunde kann seine initialen Registrierungsdaten bearbeiten.

### ISSUE THREAD

**Issue by gourmetseasoningsake** [shtillorg/ML0719-Issues#37]
Sollten wirklich alle Daten abgeändert werden können? Welchen Sinn hat die "Bonitätsprüfung", wenn ein Neukunde danach die damit verbundenen Daten frei ändern kann (Name, Kundennummer, Firma, etc.)?

001_MAMMUT_PROFIL_RECHNUNGSUEBERSICHT_v2-1.sketch Layout: "Profil"

**Comment by eatpixel** [comment]
Korrekt, es macht sicher keinen Sinn, dass der Kunde seine Kundennummer ändern kann. Diese kommt aus dem Proffix und wird von Hydraul Technik verwaltet.

**Comment by gourmetseasoningsake** [comment]
Kundennummer ist eigentlich klar. Mein Punkt war, ob man auch die ganzen Angaben der Firma ändern kann. Theoretisch könnten sich Zahlungsunfähige mit dieser Freiheit übervorteilen. Wie auch immer, ich nehm an, dass dies anderweitig abgesichtert ist und schliesse diesen Thread.
