### ISSUE TITLE
Technische Unterlagen

### ISSUE THREAD

**Issue by markus-factum** [shtillorg/ML0719-Issues#40]
**Anpassung Seite "Technische Unterlagen"**
- Neu 4 statt 3 Kategorien
- CMS wird umgebaut (braucht's CMS überhaupt noch dafür?)
- Ordnerstruktur mit entsprechenden PDFs wird hochgeladen im Batch und entsprechend geordnet dargestellt
- 4 Ordner für 4 Kategorien
- PDF wird mit max. 3 Stufen benannt (Titel, Subzeile 1 und 2)
- Trennzeichen Semikolon
- Kann man auch eine Ordnung der Ordner/PDFs machen? Ich habe im Ordnerbeispiel 01* als Beispiel genommen

Regeln:
- Dargestellt wird nur was hochgeladen
- Beispiel 4 Ordner (standard): alle 4 Kategorien werden ausgewählt, Anzeige PDFs nach Auswahl von 4. Kategorie
- Beispiel 3 Ordner: nach Auswahl von 3. Kategorie werden alle PDFs angezeigt
- Möglichkeit Einzelne PDFs oder ganzer Ordner auszuwechseln

**Comment by markus-factum** [comment]
[750 kg.zip](https://github.com/shtillorg/ML0719-Issues/files/3966897/750.kg.zip)

**Comment by markus-factum** [comment]
[TECHNISCHE UNTERLAGEN_V2.pdf](https://github.com/shtillorg/ML0719-Issues/files/3979085/TECHNISCHE.UNTERLAGEN_V2.pdf)

[ansicht.svg.zip](https://github.com/shtillorg/ML0719-Issues/files/3979102/ansicht.svg.zip)

Ich würde die 3 Spalten-Ansicht der PDFs belassen, was meinst?

**Comment by markus-factum** [comment]
Ordnerbeschriftung:
- Kann man die 2. Zusatzzeile überspringen und nach dem Titel direkt auf die 3. Zeile springen:
Beispiel: 01#Titel;;Art.-Nr. 01-02
(Grund: bei mehreren Dokumenten soll die Artikel-Nr. immer auf der 3. Zeile sein und somit bündig. Manche Dokumente haben ein 2. Zusatzzeile, manche nicht)

**Comment by gourmetseasoningsake** [comment]
Test

**Comment by markus-factum** [comment]
Test-Ordner 750 kg:
https://we.tl/t-0unbzH66me

**Comment by markus-factum** [comment]
[001_MAMMUT_TECHNISCHE-UNTERLAGEN_V2.sketch.zip](https://github.com/shtillorg/ML0719-Issues/files/4045820/001_MAMMUT_TECHNISCHE-UNTERLAGEN_V2.sketch.zip)
- Kleine Anpassungen zum Layout

**Comment by gourmetseasoningsake** [comment]
Ok

**Comment by gourmetseasoningsake** [comment]
Schliesse trotz offener franz. Version

**Comment by gourmetseasoningsake** [comment]
Franz. Version ist vorbereitet. Offen bleibt das erstellen der Seite im CMS inkl. Zuweisung der Templates.

**Comment by markus-factum** [comment]
können wir heute kurz besprechen?

**Comment by gourmetseasoningsake** [comment]
ok

**Comment by markus-factum** [comment]
Kann das System auch weitere Dokumenten-Arten handeln? Sprich der Kunde hat jetzt noch den Wunsch angebracht Excel-Dokumente hochladen zu wollen. 
A) Technisch möglich
B) Mehraufwand

Weiterhin müsste man dann eigentlich auch die Download-Icons anpassen, lass uns mal kurz telefonieren.

**Comment by gourmetseasoningsake** [comment]
Man könnte irgendwelche files hochladen, auch excel. Aber nicht alle einfach so ansehen. Insbesondere excel. Bin ab 14 erreichbar.

Vom Knochen gesendet.
