### ISSUE TITLE
Integration Whatsapp bei 2 Unterseiten

### ISSUE THREAD

**Issue by markus-factum** [shtillorg/ML0719-Issues#42]
Unterseiten WERKSTATT und ERSATZTEILLAGER 
- Whatsapp-Icon mit Telefonnummer bei den beiden Kontakten
- Funktionalität: öffnet Whatsapp auf mobilen Geräten (Nummer als Empfänger)
- Desktop weglassen
- Layout von uns für Aufwand berechnen

**Comment by gourmetseasoningsake** [comment]
Inaktiv.

**Comment by gourmetseasoningsake** [comment]
Wird mit einem einfachen click-to-chat link umgesetzt. Die Business-App ist nicht notwendig. Sollte Whatsapp aufm Endgerät nicht verfügbar sein, führt der link zu einer Webpage von Whatsapp, auf der eine Nachricht an die entsprechende Nummer gesendet werden kann und zum Download der App aufgefordert wird.

**Comment by markus-factum** [comment]
Hier noch die Handynummer:
076 443 60 33

**Comment by gourmetseasoningsake** [comment]
Unter Kollektionen -> Standorte findet man nun 3 neue Felder:

Telefonnummer Whatsapp,
Whatsapp Platzhalter-Text DE (optional) und
Whatsapp Platzhalter-Text FR (optional)

Die Platzhalter-Texte erscheinen im Whatsapp-Textfelt.
Die oben erwähnte Nummer ist bereits eingefügt.
