### ISSUE TITLE
Nummerierung Garantie-Anträge

### ISSUE THREAD

**Issue by markus-factum** [shtillorg/ML0719-Issues#45]
Der Kunde wünscht sich eine fortlaufende Auftrags-Nummer für die Garantie-Anträge. 
- Antragssteller im E-Mail
- Mammut im E-Mail sowie im CMS-Formular-Eintrag

Es kann die fortlaufende "Response"-Nummer vom CMS verwendet werden falls diese fürs E-Mail herausgezogen werden kann. Falls nicht, bräuchten wir eine Lösung um dies noch zu implementieren.

**Comment by markus-factum** [comment]
Update:
- Der Kunde wünscht dass die Garantie-Anträge eine fortlaufende Nummerierung einzigartig für die Garantie-Anträge kriegt.
- somit ist die CMS Lauf-Nr. keine Option
- Die Nummerierung soll wie folgt passieren:
- GA2020-001 (GA = Garantie-Antrag / 2020 = Jahr / 001 = Lauf-Nr.)
- Automatische Nummer-Wechsel im neuen Jahr
- Diese Laufnummer soll erscheinen:
- Im CMS-Formular (an erster Stelle)
- In beiden E-Mails (an Sender und Mammut)

Bräuchte hierzu nochmals einen Zeit-/Kosten-Aufwand.

Als kleiner Vor-Auftrag müssen wir die Pflichtfelder wieder mit einem * markieren. Kann ich das selbst machen?

**Comment by markus-factum** [comment]
Sorry * Plichtfelder kann ich selber alles erledigen.

**Comment by gourmetseasoningsake** [comment]
>     * Im CMS-Formular (an erster Stelle)
Im Backend oder auf der öffentlichen Formularseite?

**Comment by gourmetseasoningsake** [comment]
>     * GA2020-001 (GA = Garantie-Antrag / 2020 = Jahr / 001 = Lauf-Nr.)
Wir eine solche ID "schlussendlich" allein vom CMS generiert? Bzw, werden diese IDs nicht auch von proffix generiert?

**Comment by markus-factum** [comment]
- CMS-Formular im Backend
- Garantie-Antrag ist unabhängig von Proffix 
Lass uns heute Nachmittag nochmals kurz telefonieren

**Comment by gourmetseasoningsake** [comment]
Ok

Vom Knochen gesendet.
