### ISSUE TITLE
Scroll down button auf Homepage

### ISSUE THREAD

**Issue by markus-factum** [shtillorg/ML0719-Issues#46]
Der Scroll-down button sollte gemäss Layout bei jedem neuen Thema wiederholt werden, siehe PDF.
[01-hp-scroll-button.pdf](https://github.com/shtillorg/ML0719-Issues/files/4085159/01-hp-scroll-button.pdf)

**Comment by gourmetseasoningsake** [comment]
meh...

**Comment by gourmetseasoningsake** [comment]
Inaktiv.

**Comment by gourmetseasoningsake** [comment]
Hab die Pfeile soeben eingefügt. Allerdings bin ich mir nicht 100% sicher, ob das so richtig ist. Kannst du (@markus-factum) mir die ursprünglichen Screens (.sketch) der Startseite anhängen? Merci.
