### ISSUE TITLE
SEOpt (5h)

### ISSUE THREAD

**Issue by gourmetseasoningsake** [shtillorg/ML0719-Issues#47]
Um die lästigen Bots zu unterstützen hab ich einiges unternommen. Siehe Liste. Fürs Raffinieren einer automatisch generierten Sitemap sind Einträge der Sprach-Geschwisterseiten notwendig. Am Besten wir tellen diesbezüglich demnächst.

- [x] Meta auf Kollektions-Ebene - Produkte (gourmet*, inkl ML0719)
- [ ] Meta auf Kollektions-Ebene - News (gourmet*, inkl ML0719)
- [x] Ladezeit-Opt Produkte (gourmet*, 3h)
- [x] Kanonische Links (automatisch) (gourmet*, inkl ML0719)
- [x] Angabemöglichkeit Sprach-Geschwisterseiten mittles hreflang (gourmet*, inkl ML0719)
- [ ] Einträge der Sprach-Geschwisterseiten (Markus)
- [ ] Komplettes automatisches sitemap (abhängig von den Einträgen der Sprachgeschwisterseiten) (gourmet*, 2h)
- [ ] Eventuell structured data (json+ld) einfügen (gourmet*, 3h, QUESTION)

**Comment by markus-factum** [comment]
Lass uns telefonieren, heute oder Montag.

**Comment by lump** [comment]
Why did you tag me?

**Comment by gourmetseasoningsake** [comment]
> Why did you tag me?

Sorry, wasn't meant for you.

**Comment by markus-factum** [comment]
lump :-)

**Comment by jimfeld** [comment]
Test

**Comment by gourmetseasoningsake** [comment]
inaktiv
