### ISSUE TITLE
Hinzufügen neuer Betriebsabteilungen, sowie Steuerung der Anzahl Mitarbeiter pro Reihe über das CMS ermöglichen.

### ISSUE THREAD

**Issue by gourmetseasoningsake** [shtillorg/ML0719-Issues#50]
[Arrangieren-Team-Seite-170220.pdf](https://github.com/shtillorg/ML0719-Issues/files/4219936/Arrangieren-Team-Seite-170220.pdf)
(Anfrage von Mike Bolliger)

**Comment by markus-factum** [comment]
Stand neu ist, dass im Team Werkstatt 2 Reihen à je 2 Mitarbeiter stehen sollen. Gemäss Telefonat kann das im CMS mit einer "Umbruch"-Option ohne grossen Aufwand gelöst werden. Falls nicht bitte die Option hard coden einplanen.

Bis wann könntest das erledigen?

**Comment by gourmetseasoningsake** [comment]
Den Sektionen mit den Abteilungen können nun Layouts zugewiesen werden. Siehe Kollektion Abteilungen. Die Handles werden nicht mehr benötigt.
