### ISSUE TITLE
Plakette auswechseln

### ISSUE THREAD

**Issue by markus-factum** [shtillorg/ML0719-Issues#51]
die Plakette unter Hebebühnenservice (L- und XL-Service) muss ausgewechselt werden, wegen neuer Telefonnummer. SVG im Anhang. Wieviel Aufwand?
[lift-badge-v2.svg.zip](https://github.com/shtillorg/ML0719-Issues/files/4287924/lift-badge-v2.svg.zip)

**Comment by gourmetseasoningsake** [comment]
ist erledigt. kostet nichts

**Comment by markus-factum** [comment]
haha, danke :-)

**Comment by gourmetseasoningsake** [comment]
easy :)
