### ISSUE TITLE
Karriere (1h)

### ISSUE THREAD

**Issue by markus-factum** [shtillorg/ML0719-Issues#52]
Neue Seite KARRIERE
- Unter der Rubrik NEWS
- V1: Text: Subline an erster Stelle, Headline an zweiter Stelle
- V1: PDF Upload und Preview
- V1: Button "Mehr erfahren" öffnet PDF im Browser
- V2: Nur Text: Headline an erster Stelle, Subline an zweiter Stelle
- DE und FR

Kannst Du mir bitte den Aufwand dazu bis Montag durchgeben? Danke Markus
[001_MAMMUT_V10_KARRIERE.sketch.zip](https://github.com/shtillorg/ML0719-Issues/files/4298262/001_MAMMUT_V10_KARRIERE.sketch.zip)

**Comment by gourmetseasoningsake** [comment]
Ok

Vom Knochen gesendet.

**Comment by gourmetseasoningsake** [comment]
1 Stunde. Würde das als "enhancement running" abstempeln.

**Comment by gourmetseasoningsake** [comment]
Beim Erstellen der PDFs sollte man bezüglich Indizierung gleich wie bei einer gewöhnlichen Page auf einige Dinge achten. Z.B. wird das [hier](https://www.mightycitizen.com/insights/articles/seo-for-pdfs-optimizing-your-pdf-files-for-search) erklärt.

**Comment by markus-factum** [comment]
Cool danke und danke für Info bzg. PDF.

**Comment by markus-factum** [comment]
Kannst Du bis morgen bitte aufschalten? Wäre kuul. Danke.

**Comment by gourmetseasoningsake** [comment]
bisschen kurzfristig, min jung, auch wenn nur ne stunde. aber ist erledigt.

https://mammut-lift.ch/de/news/karriere
https://mammut-lift.ch/fr/nouvelles/carriere

beide seiten sind momentan von der navi ausgeschlossen.

**Comment by markus-factum** [comment]
Sorry, bis morgen war eigentlicht bis heute Abend gedacht. Werde mich nächstes Mal genauer ausdrucken!
