### ISSUE TITLE
Zusammenführung rechtliche Hinweise

### ISSUE THREAD

**Issue by markus-factum** [shtillorg/ML0719-Issues#53]
- die 3 Seiten mit den Rechtlichen Hinweisen (AGB, Rechtliche Hinweise und Garantiebedingungen) sollen auf einer Unterseite zusammengeführt werden
- zweite Navigationsebene, wie bei Produkte verwenden
- die 3 Seiten soll nach wie vor direkt aufgerufen werden können
- allfällige zukünftige Seiten sollen angehängt werden können

Bitte im 1. Schritt mir die Kosten durchgeben. Kannst mir das bis morgen liefern?

Danke, Lump
[001_MAMMUT_V10_RECHTLICHE HINWEISE.sketch.zip](https://github.com/shtillorg/ML0719-Issues/files/4324973/001_MAMMUT_V10_RECHTLICHE.HINWEISE.sketch.zip)

**Comment by gourmetseasoningsake** [comment]
1h

**Comment by gourmetseasoningsake** [comment]
Um weitere rechtliche Seiten hinzzufügen, kann die Vorlage einer drei bestehenden Seiten verwendet und die Seite der entsprechenden _Navigationsgruppe_ zugeteilt werden.
Die Navigationsgruppen heissen _Legal Topbar_.
