### ISSUE TITLE
Filter Funktion

### ISSUE THREAD

**Issue by gourmetseasoningsake** [shtillorg/ML0719-Issues#56]
Ein Ansatz liegt bereit auf der Live-site. Das Design und die Funktionalität sind teilweise nach Gutdünken erstellt. Sinnvoll wären aktualisierte Screens mit mehr oder minder aufschlussreichen Beschrieben zur Funktionalität und Benutzerführung, da die letzten nicht mehr die aktuellen "Anforderungen" widerspiegeln. Bin bis Montag aus dem Spiel.

**Comment by eatpixel** [comment]
Der Kunde hat den "Ansatz" auf der Live Seite bereits abgenommen. Die Inhalte auf der Linken Seite sollen aus den Vorgaben des Proffix entnommen werden und dort im Stil der Live Seite aufgeschalten werden.

**Comment by gourmetseasoningsake** [comment]
Nur um das noch festzuhalten: Die Auswahl-/Filtermöglichkeiten sind hard-coded. Sollten sich diese Vorgaben ändern, muss man sie manuell im Code entsprechend anpassen.

**Comment by gourmetseasoningsake** [comment]
Die Verknüpfungen (gemäss Web-Shop-Details.xls) zwischen Kategorie und Gruppe stimmen nicht mehr. Wie kann es z.B. sein, dass ZE.20516 in der Kat. 11 und in Gruppe 132 ist?

Sollte sich hierbei etwas geändert haben, benötige ich ein aktuelles Web-Shop-Details.xls. (Die hierfür benötigte Info lässt sich nicht einfach aus der Rest API herauslesen)

**Comment by eatpixel** [comment]
Wurde beim Kunden platziert diese Anfrage.

**Comment by gourmetseasoningsake** [comment]
Per E-Mail: "Da haben sie wohl einen Fehler gemacht bei dem Produkt, dass du erwähnt hast. Ich habe Beat darauf hingewiesen, dass wir bis jetzt nur Testdaten hatten." -> D.h. die Verknüpfungen (gemäss Web-Shop-Details.xls) gelten noch.
