### ISSUE TITLE
Discounts für Kunden sollen verwaltet werden können.

### ISSUE THREAD

**Issue by gourmetseasoningsake** [shtillorg/ML0719-Issues#59]
Benötigt nähere Angaben.

**Comment by eatpixel** [comment]
Im Proffix werden jedem Kunden eigene Rabatte zugeteilt. Diese Rabatte sollen sich im Webshop wiederspiegeln. 
![Bildschirmfoto_2020-06-03_um_09_39_57](https://user-images.githubusercontent.com/742012/83609221-4167b780-a57e-11ea-8c43-04b0cf09c5d7.jpg)

**Comment by eatpixel** [comment]
![Unknown](https://user-images.githubusercontent.com/742012/83757409-b61b1e80-a670-11ea-8252-eb3b67b1cfa2.png)
hier noch das bessere Bild von Kunden.

**Comment by gourmetseasoningsake** [comment]
Wo sollen sich diese Rabatte widerspiegeln? In den Screens von 001_MAMMUT_V10_Shop.sketch werden keine Rabatte behandelt.

**Comment by eatpixel** [comment]
Die Rabatte sind ja Kundenpreise. Das heisst, jeder Kunde hat andere Preise dargestellt. Es ist nicht nötig dies im Layout auszuzeichnen. Für den Kunden sind die "Rabatte" einfach seine Einkaufspreise.

**Comment by gourmetseasoningsake** [comment]
Notiz für mich: Preise werden in allen Ansichten (Card, Details, Line-Items, etc.) mit dem bereits abgzogenen Kundenrabatt (falls vorhanden) dargestellt.
