### ISSUE TITLE
Nur eine bestimmte Auswahl der verf. Artikel soll angezeigt werden.

### ISSUE THREAD

**Issue by gourmetseasoningsake** [shtillorg/ML0719-Issues#61]
Sicher ist: Nur Artikel, die für den Webshop aktiviert sind (mittels Checkbox in der Proffix Oberfläche).

Sollen nun von dieser Menge nur diejenigen angezeigt werden, die ein Bild haben, oder werden die restilichen Bilder noch nachgeliefert?

**Comment by eatpixel** [comment]
die restlichen Bilder werden noch nachgeliefert. Ich habe aber für den Notfall Platzhalter bestellt.
